### Output configuration
#
# Default wallpaper (more resolutions are available in /usr/share/backgrounds/sway/)
# Requires: desktop-backgrounds-compat, swaybg
output * bg /usr/share/backgrounds/default.png fill
# You can get the names of your outputs by running: swaymsg -t get_outputs
output eDP-1 scale 1.5
output DP-5 scale 1.5
output DP-5 resolution 3840x2160 position 0 0
output eDP-1 resolution 2256x1504 position 2560 0
output * adaptive_sync on
# Borders
output * adaptive_sync on
default_border pixel 3
default_floating_border pixel 3
gaps inner  5
gaps outer  1
gaps top  1
gaps bottom  1
bindsym $mod+shift+g exec swaymsg gaps outer all set 0 && swaymsg gaps inner all set 5 
bindsym $mod+g exec swaymsg gaps outer all set 0 && swaymsg gaps inner all set 0
# Activate smart borders (always)
smart_borders on
hide_edge_borders smart
# Hide gaps when there is only 1 window
smart_gaps on
