# Move all worksapces to current output when switching (helps with multihead)
# https://github.com/swaywm/sway/wiki#move-workspace-to-current-output-when-switching
bindsym --no-warn $mod+1 [workspace="1"] move workspace to output current; workspace number 1
bindsym --no-warn $mod+2 [workspace="2"] move workspace to output current; workspace number 2
bindsym --no-warn $mod+3 [workspace="3"] move workspace to output current; workspace number 3
bindsym --no-warn $mod+4 [workspace="4"] move workspace to output current; workspace number 4
bindsym --no-warn $mod+5 [workspace="5"] move workspace to output current; workspace number 5
bindsym --no-warn $mod+6 [workspace="6"] move workspace to output current; workspace number 6
bindsym --no-warn $mod+7 [workspace="7"] move workspace to output current; workspace number 7
bindsym --no-warn $mod+8 [workspace="8"] move workspace to output current; workspace number 8
bindsym --no-warn $mod+9 [workspace="9"] move workspace to output current; workspace number 9
bindsym --no-warn $mod+0 [workspace="0"] move workspace to output current; workspace number 10
