# Tokyo night
# https://github.com/stronk-dev/Tokyo-Night-Linux/blob/master/.config/sway/config
client.focused           #9aa5ce #16161d #c0caf5 #9aa5ce   #9aa5ce
client.focused_inactive  #16161d #16161d #c0caf5 #16161d   #16161d
client.unfocused         #16161d #16161d #c0caf5 #16161d   #16161d

# Rofi
# https://github.com/Murzchnvok/rofi-collection/tree/master/tokyonight
set $menu rofi \
	-no-lazy-grab \
	-show drun \
	-modi drun \
	-theme "$HOME/.config/rofi/tokyonight.rasi"
bindsym --no-warn $mod+d exec $menu


set $rofi_power rofi -show p -modi p:"$HOME/.config/rofi/off.sh" -theme "$HOME/.config/rofi/powermenu_theme.rasi"
bindsym $mod+Shift+d exec $rofi_power
