# Your preferred terminal emulator
# Recommends: foot
set $term foot -e distrobox enter dev
set $termfloat foot -a termfloat -e distrobox enter dev
#set $term foot -e distrobox enter dev -- tmux new -As0
set $hostterm foot

# Start a terminal
bindsym --no-warn $mod+Return exec $term
bindsym $mod+Shift+Return exec $termfloat
bindsym $mod+Ctrl+Return exec $hostterm
