#swaymsg -t get_tree | grep app_id
    for_window [app_id="^menu$"]                                       floating enable, border none
    #for_window [floating]                                              border none
    for_window [app_id="pop-up"]                                       floating enable
    for_window [app_id="bubble"]                                       floating enable 
    for_window [app_id="task_dialog"]                                  floating enable
    for_window [app_id="Preferences"]                                  floating enable
    for_window [app_id="dialog"]                                       floating enable 
    for_window [app_id="menu"]                                         floating enable
    for_window [app_id="Organizer"]                                    floating enable
    for_window [app_id="About"]                                        floating enable
    for_window [app_id="toolbox"]                                      floating enable
    for_window [app_id="page-info"]                                    floating enable	
    for_window [app_id="webconsole"]                                   floating enable
    for_window [app_id="termfloat"]                                    floating enable
    for_window [app_id="termfloat"]                                    resize set height 540
    for_window [app_id="termfloat"]                                    resize set width 960
    for_window [app_id="pavucontrol"]                                  floating enable
    for_window [app_id="pavucontrol"]                                  resize set height 540
    for_window [app_id="pavucontrol"]                                  resize set width 960
    for_window [app_id="mpv"]                                          floating enable 
    for_window [app_id="mpv"]                                          resize set height 540
    for_window [app_id="mpv"]                                          resize set width 960
    for_window [class="vlc"]                                           floating enable 
    for_window [class="vlc"]                                           resize set height 540
    for_window [class="vlc"]                                           resize set width 960
    for_window [app_id="thunar"]                                       floating enable 
    for_window [app_id="thunar"]                                       resize set height 540
    for_window [app_id="thunar"]                                       resize set width 960
    for_window [app_id="nemo"]                                         floating enable 
    for_window [app_id="nemo"]                                         resize set height 540
    for_window [app_id="nemo"]                                         resize set width 960
    for_window [app_id=".*Flatseal.*"]                                  floating enable
    for_window [title="ssh-askpass"]                                   floating enable
    for_window [title="(?:Open|Save) (?:File|Folder|As)"]              floating enable; sticky enable
    for_window [app_id="Firefox" title="^Picture-in-Picture$"]         floating enable; sticky enable; border none
    for_window [app_id="Firefox"]                                      inhibit_idle fullscreen
    for_window [app_id="Firefox" title="Firefox - Sharing Indicator"]  kill
    for_window [app_id="chromium"]                                     inhibit_idle fullscreen
    for_window [class="Sparrow" title="^Wallet Password"]              floating enable; sticky enable
    for_window [app_id="org.keepassxc.KeePassXC"]                      floating enable
