#!/bin/sh

# File preview handler for lf.

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

case "$(file --dereference --brief --mime-type -- "$1")" in
	text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1"  ;;
	text/* | */xml | application/json) bat --terminal-width "$4" -f "$1" ;;
	application/zip|application/gzip|application/x-xz|application/x-tar) atool --list -- "$1" ;;
	audio/* | application/octet-stream) mediainfo "$1" || exit 1;;
	video/* ) mediainfo "$1" || exit 1;;
	*opendocument*) odt2txt "$1" ;;
	application/pgp-encrypted) gpg -d -- "$1" ;;
	image/*) catimg -w 90 - "$1" ;;
	#image/*) img2sixel -h 120 -w 240 "$1" ;;
esac

