[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }
auto-format = true

[language-server.ruff]
command = "ruff server"

[[language]]
name = "toml"
language-servers = ["taplo"]
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "yaml"
language-servers = ["yaml-language-server"]

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https=//raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json" = "docker-compose.yaml"
"https=//json.schemastore.org/github-workflow.json" = ".github/workflows/*.yaml"
"https=//json.schemastore.org/github-action.json" = ".github/actions/*/action.yaml"

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "shfmt", args = ["-i", "4"] }
auto-format = true

[[language]]
name = "typst"
language-servers = ["tinymist"]
formatter = { command = "typstyle" }
auto-format = true

[language-server.tinymist]
command = "tinymist"
config = { tinymist.formatterMode = "typstyle" }
